apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
- namespace.yaml
- api-service.yaml
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- mutating-webhook-configuration.yaml
- service-account.yaml
- service.yaml
- validating-webhook-configuration.yaml
commonLabels:
  kustomize.component: cert-manager
images:
- name: docker.io/mrxinwang/cert-manager-controller-arm64
  newName: docker.io/mrxinwang/cert-manager-controller-arm64
  newTag: v0.11.0
- name: docker.io/mrxinwang/cert-manager-webhook-arm64
  newName: docker.io/mrxinwang/cert-manager-webhook-arm64
  newTag: v0.11.0
- name: docker.io/mrxinwang/cert-manager-cainjector-arm64
  newName: docker.io/mrxinwang/cert-manager-cainjector-arm64
  newTag: v0.11.0
configMapGenerator:
- name: cert-manager-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: cert-manager-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
configurations:
- params.yaml
