apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameprefix: ml-pipeline-
commonLabels:
  app: ml-pipeline-persistenceagent
resources:
- clusterrole-binding.yaml
- clusterrole.yaml
- deployment.yaml
- service-account.yaml
images:
- name: mrxinwang/ml-pipeline-persistenceagent
  newTag: 0.2.0
  newName: mrxinwang/ml-pipeline-persistenceagent
