namePrefix: metadata-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kustomize.component: metadata
configMapGenerator:
- name: ui-parameters
  env: params.env
- name: grpc-configmap
  env: grpc-params.env
generatorOptions:
  # TFX pipelines use metadata-grpc-configmap for finding grpc server host and
  # port at runtime. Because they don't know the suffix, we have to disable it.
  disableNameSuffixHash: true
resources:
- metadata-deployment.yaml
- metadata-service.yaml
- metadata-ui-deployment.yaml
- metadata-ui-role.yaml
- metadata-ui-rolebinding.yaml
- metadata-ui-sa.yaml
- metadata-ui-service.yaml
- metadata-envoy-deployment.yaml
- metadata-envoy-service.yaml
namespace: kubeflow
vars:
- name: ui-namespace
  objref:
    kind: Service
    name: ui
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
- name: ui-clusterDomain
  objref:
    kind: ConfigMap
    name: ui-parameters
    version: v1
  fieldref:
    fieldpath: data.uiClusterDomain
- name: service
  objref:
    kind: Service
    name: ui
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
- name: metadata-envoy-service
  objref:
    kind: Service
    name: envoy-service
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
images:
- name: mrxinwang/metadata
  newName: mrxinwang/metadata
  newTag: latest
- name: mrxinwang/ml_metadata_store_server
  newName: mrxinwang/ml_metadata_store_server
  newTag: v0.21.1
- name: mrxinwang/ml-pipeline-envoy-metadata-grpc
  newName: mrxinwang/ml-pipeline-envoy-metadata-grpc
  newTag: v0.2.0
- name: mrxinwang/mysql_arm64_updated
  newName: mrxinwang/mysql_arm64_updated
  newTag: 8.0.17
- name: mrxinwang/metadata-frontend
  newName: mrxinwang/metadata-frontend
  newTag: latest
